version: 0.2

phases:
  install:
    commands:
      - echo Installing RSpec...
      - gem install rspec
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
      - docker-compose up -d
  build:
    commands:
      - echo Build started on `date`
      - rspec hello_world_spec.rb
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
    - hello_world.rb
