version: '2'
services:
  postgres:
    image: "postgres:9.6.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
  redis:
    image: "redis:2.8.9"
    ports:
      - "6379:6379"
